version: '3.1'

services:

  redmine:
    image: redmine
    container_name: Redmine
    hostname: Redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: 7^mX7n$#2HCXx96%rG&Hf%TWqqKU@i9D
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7^mX7n$#2HCXx96%rG&Hf%TWqqKU@i9D
      MYSQL_DATABASE: redmine